# Generated by CMake 2.8.9

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target YARP_OS
ADD_LIBRARY(YARP_OS SHARED IMPORTED)

# Create imported target YARP_sig
ADD_LIBRARY(YARP_sig SHARED IMPORTED)

# Create imported target YARP_math
ADD_LIBRARY(YARP_math SHARED IMPORTED)

# Create imported target YARP_dev
ADD_LIBRARY(YARP_dev SHARED IMPORTED)

# Create imported target wire_rep_utils
ADD_LIBRARY(wire_rep_utils SHARED IMPORTED)

# Create imported target xmlrpc_carrier
ADD_LIBRARY(xmlrpc_carrier SHARED IMPORTED)

# Create imported target tcpros_carrier
ADD_LIBRARY(tcpros_carrier SHARED IMPORTED)

# Create imported target bayer_carrier
ADD_LIBRARY(bayer_carrier SHARED IMPORTED)

# Create imported target priority_carrier
ADD_LIBRARY(priority_carrier SHARED IMPORTED)

# Create imported target yarpcar
ADD_LIBRARY(yarpcar SHARED IMPORTED)

# Create imported target YARP_name
ADD_LIBRARY(YARP_name SHARED IMPORTED)

# Create imported target YARP_init
ADD_LIBRARY(YARP_init SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/YARP-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
